//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareShopClient.HSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HSService.IHSService")]
    public interface IHSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHSService/GetProducts", ReplyAction="http://tempuri.org/IHSService/GetProductsResponse")]
        System.Collections.ObjectModel.ObservableCollection<HardwareShop.Entities.Product> GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHSService/GetCustomer", ReplyAction="http://tempuri.org/IHSService/GetCustomerResponse")]
        System.Collections.ObjectModel.ObservableCollection<HardwareShop.Entities.Customer> GetCustomer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHSService/SubmitOrder", ReplyAction="http://tempuri.org/IHSService/SubmitOrderResponse")]
        void SubmitOrder(HardwareShop.Entities.Order order);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHSServiceChannel : HardwareShopClient.HSService.IHSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HSServiceClient : System.ServiceModel.ClientBase<HardwareShopClient.HSService.IHSService>, HardwareShopClient.HSService.IHSService {
        
        public HSServiceClient() {
        }
        
        public HSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.ObjectModel.ObservableCollection<HardwareShop.Entities.Product> GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Collections.ObjectModel.ObservableCollection<HardwareShop.Entities.Customer> GetCustomer() {
            return base.Channel.GetCustomer();
        }
        
        public void SubmitOrder(HardwareShop.Entities.Order order) {
            base.Channel.SubmitOrder(order);
        }
    }
}
